// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectstreamer.actions;

import java.util.Optional;
import com.mendix.core.Core;
import com.mendix.datastorage.XPathBasicQuery;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import objectstreamer.config.StreamObjectConfigurationFactory;
import objectstreamer.usecase.JsonMapperImpl;
import objectstreamer.usecase.ObjectStreamer;
import objectstreamer.usecase.StreamObjectConfiguration;

public class StreamObjectsREST extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String entityforExport;
	private java.lang.String constraint;
	private java.lang.String sortAttribute;
	private java.lang.Long batchSize;
	private java.lang.String exportMapping;

	public StreamObjectsREST(IContext context, java.lang.String entityforExport, java.lang.String constraint, java.lang.String sortAttribute, java.lang.Long batchSize, java.lang.String exportMapping)
	{
		super(context);
		this.entityforExport = entityforExport;
		this.constraint = constraint;
		this.sortAttribute = sortAttribute;
		this.batchSize = batchSize;
		this.exportMapping = exportMapping;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
		String notNullableConstaint = Optional.ofNullable(this.constraint).orElse("");
		
		XPathBasicQuery xPathQuery = Core.createXPathQuery(String.format("//%s%s", this.entityforExport, notNullableConstaint))
				.setAmount(batchSize.intValue())
				.addSort(sortAttribute, true);
		
		StreamObjectConfigurationFactory factory = new StreamObjectConfigurationFactory();
		
		StreamObjectConfiguration streamObjectConfiguration = factory.create("Http");
		streamObjectConfiguration.setContext(context);
		streamObjectConfiguration.setXPathQuery(xPathQuery);
		
		JsonMapperImpl jsonMapper = (JsonMapperImpl) streamObjectConfiguration.getJsonMapper();
		jsonMapper.setExportMapping(this.exportMapping);
		
		ObjectStreamer objectStreamer = new ObjectStreamer(streamObjectConfiguration);
		objectStreamer.stream();
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StreamObjectsREST";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
